version: 2

workflows:
  version: 2
  build:
    jobs:
      - gh-pages-deploy:
          # Run this job only on master
          filters:
            branches:
              only: master

jobs:
  gh-pages-deploy:
    # Docker image to use for this job
    docker:
      - image: ruby:2.5
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd docs
            bundle install --path vendor/bundle
      - add_ssh_keys:
          fingerprints: [ "bd:07:5f:84:3b:0c:41:3d:7b:04:50:17:27:bf:7d:a0" ]
      - run:
          name: Build and deploy
          command: ./deploy.sh



